---
title: "Monitoring the Covid-19 Pandemic in Scotland"
date: "`r format(Sys.time(), '%d %B, %Y')`" 
header-includes:
   - \usepackage{booktabs}
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{caption}
   - \captionsetup[figure]{labelformat=empty}
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    toc: no
classoption: landscape
---


```{r setup, include=FALSE}
#date: "`r format(Sys.time(), '%d %B, %Y')`" 
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = 'H')
# Load packages
library(flexdashboard) ; library(shiny) ; library(readr); library(dplyr); library(tidyr); library(purrr); library(forcats); library(stringr); library(htmlwidgets); library(lubridate); library(sf); library(RcppRoll); library(plotly); library(shinythemes);library(leaflet); library(classInt); library(ggrepel); library(scales); library(leaflet.extras); library(RColorBrewer);library(toOrdinal);library(knitr);library(kableExtra);library(RcppRoll);
library(colorblindr); library(readxl);library(spatstat.utils);library(httr);library(cowplot); library(viridis);
library(patchwork)

#source("growth_rate_window.R")
source("weekly_ratios_2.R")
weekly_ratios <- weekly_ratios_2
#source("weekly_ratios_byday.R")


# Import hospital data
## Covid daily hospital data
myurl <- "https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/04/coronavirus-covid-19-trends-in-daily-data/documents/trends-in-number-of-people-in-hospital-with-confirmed-or-suspected-covid-19/trends-in-number-of-people-in-hospital-with-confirmed-or-suspected-covid-19/govscot%3Adocument/Trends%2Bin%2Bdaily%2BCOVID-19%2Bdata%2B-%2B110520.xlsx?forceDownload=true"
#myurl <- "https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/04/trends-in-number-of-people-in-hospital-with-confirmed-or-suspected-covid-19/documents/trends-in-number-of-people-in-hospital-with-confirmed-or-suspected-covid-19/trends-in-number-of-people-in-hospital-with-confirmed-or-suspected-covid-19/govscot%3Adocument/Data%2BTable%2B%252810-04-2020%2529.xlsx?forceDownload=true"
GET(myurl, write_disk(tmp <- tempfile(fileext = ".xlsx")))
GET(myurl, write_disk("hps_daily.xlsx", overwrite = TRUE))

#data_hosp <- read_excel(tmp, sheet = "Table 1", skip = 3)
data_hosp <- read_excel(tmp, sheet = "Table 2 - Hospital Care", skip = 3)

data_hosp <- data_hosp %>%
  rename("date" = "...1",
         "ICU_confirmed" = "Confirmed...2",
         "ICU_suspected" ="Suspected...3", 
         "ICU_total" = "Total...4",
         "Hospital_confirmed" = "Confirmed...5",
         "Hospital_suspected" = "Suspected...6",
         "Hospital_total" = "Total...7" ) %>%
  filter(!is.na(ICU_total)) %>%
  mutate(date = lubridate::ymd(date)) %>%
  mutate(ICU_confsusp = case_when(is.na(ICU_confirmed) & is.na(ICU_suspected) ~ ICU_total)) %>%
  mutate(Hospital_confsusp = case_when(is.na(Hospital_confirmed) & is.na(Hospital_suspected) ~ Hospital_total)) %>%
  select(date, contains("ICU"), everything()) %>%
  mutate(date = date - days(1))

data_hosp_icu <- data_hosp %>%
  select(date, contains("ICU")) %>%
  pivot_longer(cols = c(ICU_confirmed, ICU_suspected, ICU_confsusp), names_to = "Patients", values_to = "Number") %>%
  mutate(Patients = recode(Patients,  "ICU_confsusp" = "Confirmed/Suspected", 
                           "ICU_confirmed" = "Confirmed", 
                           "ICU_suspected" = "Suspected")) %>%
  mutate(Patients = factor(Patients, levels = c("Confirmed/Suspected", "Suspected", "Confirmed")))



data_hosp_hosp <- data_hosp %>%
  select(date, contains("hospital")) %>%
  pivot_longer(cols = c(Hospital_confirmed, Hospital_suspected, Hospital_confsusp), names_to = "Patients", values_to = "Number") %>%
  mutate(Patients = recode(Patients,  "Hospital_confsusp" = "Confirmed/Suspected", 
                           "Hospital_confirmed" = "Confirmed", 
                           "Hospital_suspected" = "Suspected")) %>%
  mutate(Patients = factor(Patients, levels = c("Confirmed/Suspected", "Suspected", "Confirmed")))

wk_gr_hosp_icu <- data_hosp %>%
       mutate(ICU_prev = lag(ICU_total , 7), 
         weekdays(date)) %>%
       filter(date >= ymd("2020-03-25")) %>%
       #pivot_longer(c(ICU_total, ICU_prev), names_to = "week", values_to = "number") %>%
      group_by(date) %>%
      nest() %>%
      mutate(tab = map(data, ~ weekly_ratios_ci(.x$ICU_total, .x$ICU_prev))) %>%
  mutate(ratio_m = map_dbl(tab, ~parse_number(as.character((.x[1,2]))))) %>% 
  mutate(lci = map_dbl(tab, ~parse_number(as.character((.x[2,2]))))) %>% 
  mutate(uci = map_dbl(tab, ~parse_number(as.character((.x[3,2]))))) %>% 
  ungroup() %>%
  select(date, ratio_m, lci, uci) %>%
  mutate(comparison = if_else(ratio_m >1, "greater than", "less than")) %>%
  significance_wk() 


wk_gr_hosp_icu_latest <- filter(wk_gr_hosp_icu, date == max(wk_gr_hosp_icu$date))

wk_gr_hosp_hosp <- data_hosp %>%
       mutate(Hosp_prev = lag(Hospital_total , 7), 
         weekdays(date)) %>%
       filter(date >= ymd("2020-03-25")) %>%
       #pivot_longer(c(Hospital_total, Hosp_prev), names_to = "week", values_to = "number") %>%
      group_by(date) %>%
      nest() %>%
      mutate(tab = map(data, ~ weekly_ratios_ci(.x$Hospital_total, .x$Hosp_prev))) %>%
  mutate(ratio_m = map_dbl(tab, ~parse_number(as.character((.x[1,2]))))) %>% 
  mutate(lci = map_dbl(tab, ~parse_number(as.character((.x[2,2]))))) %>% 
  mutate(uci = map_dbl(tab, ~parse_number(as.character((.x[3,2]))))) %>% 
  ungroup() %>%
  select(date, ratio_m, lci, uci) %>%
  mutate(comparison = if_else(ratio_m >1, "greater than", "less than")) %>%
  significance_wk() 


wk_gr_hosp_hosp_latest <- filter(wk_gr_hosp_hosp, date == max(wk_gr_hosp_icu$date))

# Import NRS data
myurl_deaths <- "https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-19.xlsx"
GET(myurl_deaths, write_disk(tmp <- tempfile(fileext = ".xlsx")))
GET(myurl_deaths, write_disk("nrs.xlsx", overwrite = TRUE))

#NRS weekly
nrs_deaths_covid_raw <- read_excel(tmp, sheet = "Table 1 - COVID deaths", skip = 3) %>%
  select(-`Year to Date`) %>%
  rename("Details" = "...2",
         "Total" = "...23")

nrs_deaths_covid <- nrs_deaths_covid_raw %>% filter(`Week beginning` == "Deaths involving COVID-194") %>%
  pivot_longer(cols = `43829`:names(nrs_deaths_covid_raw)[ncol(nrs_deaths_covid_raw)-1],
               names_to = "week_beginning", 
               values_to = "weekly_deaths_total") %>%
  mutate(week_beginning = janitor::excel_numeric_to_date(parse_number(week_beginning))) %>%
  mutate(Type = "Covid19 deaths") %>%
  select(week_beginning, weekly_deaths_total, Type)

# NRS daily
nrs_deaths_covid_raw_daily <- read_excel(tmp, sheet = "Figure 2 data", skip =2) %>%
  filter(!is.na(Source)) %>%
  mutate(date = janitor::excel_numeric_to_date(parse_number(Date1))) %>%
  filter(Source == "NRS") %>%
  mutate(new_deaths = c(0,diff(`Cumulative Count`, 1))) 



# Import Scottish covid data
#path <- "COVID-19_Scotland_data_all_2020-04-10.xlsx" 
path <- paste0("Daily_Reports/COVID-19_Scotland_data_all_", {Sys.Date()}, ".xlsx") 
# Scottish cases data
scot_data_raw <- read_excel(path, sheet = "Cases By Health Board", skip = 1)
scot_data_raw <- filter(scot_data_raw, !Health_Board %in% c("Increase", "pIncrease")) %>%
              rename(confirmed_cases= Total,
                     Date = Health_Board) %>%
              mutate(date = lubridate::ymd(Date)) %>%
              select(-Date) 
  
scot_data_raw$date[nrow(scot_data_raw)] <- scot_data_raw$date[nrow(scot_data_raw)-1] + days(1)
#scot_data_raw$confirmed_cases[nrow(scot_data_raw)] <- 4565 ## REMOVE

scot_data_raw <- scot_data_raw %>%
              mutate(date = date - days(1))

scot_data <- scot_data_raw %>%
             mutate(new_cases = confirmed_cases - replace_na(lag(confirmed_cases),0)) %>%
             mutate(doubling_time_week = 7*log(2)/log(confirmed_cases/replace_na(lag(confirmed_cases,7),0))) 
             
# Scottish death data
scot_deaths <- read_excel(path, sheet = "Scotland Deaths", skip = 1) %>%
  rename("deaths" = Deaths_Cum, 
         "new_deaths" = Deaths_New) %>%
  mutate(doubling_time_week = 7*log(2)/log(deaths/replace_na(lag(deaths,7),0))) %>%
  mutate(date = lubridate::ymd(Date))
  

scot_deaths$date[nrow(scot_deaths)] <- scot_deaths$date[nrow(scot_deaths)-1] + days(1)

scot_deaths <- scot_deaths %>%
  mutate(date = date - days(1))

# Scottish tests
scot_tests <- read_excel(path, sheet = "CPT & DPC") 
#scot_tests$Cases[nrow(scot_tests)] <- 4565 #REMOVE

scot_tests  <- scot_tests %>%
  rename("Conducted" = Tests, 
         "Total Positive" = Cases,
         "deaths_per_case" = DPC,
         "cases_per_test" = CPT) %>%
  mutate("Conducted today" = Conducted - replace_na(lag(Conducted), 0)) %>%
  mutate("Total Negative" = Conducted - `Total Positive`) %>%
  mutate("Positive" = `Total Positive` - replace_na(lag(`Total Positive`), 0),
         "Negative" = `Total Negative` - replace_na(lag(`Total Negative`), 0)) 
scot_tests$Positive[scot_tests$Date == ymd("2020-03-12")] <- 24
scot_tests$Negative[scot_tests$Date == ymd("2020-03-12")] <- 552

  
scot_tests_long <- scot_tests %>%
pivot_longer(cols = Positive:Negative, names_to = "Result", values_to = "Number") %>%
mutate(Result = factor(Result, levels = c("Positive", "Negative")))


# Plot colours
#nice_blue <- palette_OkabeIto[5]
#nice_red <- palette_OkabeIto[6]  

nice_blue <- "#0072B2"
nice_red <- "#D55E00"
nice_green <- "#009E73"
nice_orange <- "#E69F00"

# Weekly Growth 
wk_gr_newcases <- scot_data %>% select(new_cases, date) %>%
      mutate(outcome = new_cases) %>%
       weekly_ratios() %>%
       filter(!is.na(ratio) & !is.infinite(ratio)) %>%
       significance_wk() %>%
       mutate(adjustment = "no adjustment")

wk_gr_newdeaths <- scot_deaths %>% select(new_deaths, date) %>%
      mutate(outcome = new_deaths) %>%
       weekly_ratios() %>%
       filter(!is.na(ratio) & !is.infinite(ratio)) %>%
       significance_wk()

wk_gr_newdeaths_nrs <- nrs_deaths_covid_raw_daily %>% select(new_deaths, date) %>%
      mutate(outcome = new_deaths) %>%
       weekly_ratios() %>%
       filter(!is.na(ratio) & !is.infinite(ratio)) %>%
       significance_wk()

wk_gr_newdeaths_nrs_hps <- bind_rows(wk_gr_newdeaths %>% mutate(source = "HPS"),
wk_gr_newdeaths_nrs %>% mutate(source = "NRS"))

#nrs by age
nrs_deaths_covid_week_age <- nrs_deaths_covid_raw %>% 
                             slice(9:15) %>%
                             pivot_longer(cols = `43829`:names(nrs_deaths_covid_raw)[ncol(nrs_deaths_covid_raw)-1],
               names_to = "week_beginning", 
               values_to = "weekly_deaths_total") %>%
  #mutate(Details = case_when(`Week beginning` == "Deaths involving COVID-194" ~ "All",
  #                           TRUE ~ Details)) %>%
  mutate(week_beginning = janitor::excel_numeric_to_date(parse_number(week_beginning))) %>%
  select(-`Week beginning`) %>%
  rename("Age Group" = Details) %>%
  #filter(Location != "Other institution") %>%
  select(`Age Group`, week_beginning, weekly_deaths_total) %>%
  mutate(week_ending = week_beginning + 6)

wk_gr_nrs_deaths_age <- nrs_deaths_covid_week_age %>%
  group_by(`Age Group`) %>%
  mutate(week_ending_prev = lag(weekly_deaths_total, 1)) %>%
  filter(!is.na(week_ending_prev) & week_ending_prev >0) %>% 
  ungroup() %>%
  group_by(`Age Group`, week_ending) %>%
  nest() %>%
  mutate(tab = map(data, ~ weekly_ratios_ci(.x$weekly_deaths_total, .x$week_ending_prev))) %>%
  mutate(ratio_m = map_dbl(tab, ~parse_number(as.character((.x[1,2]))))) %>% 
  mutate(lci = map_dbl(tab, ~parse_number(as.character((.x[2,2]))))) %>% 
  mutate(uci = map_dbl(tab, ~parse_number(as.character((.x[3,2]))))) %>% 
  ungroup() %>%
  select(`Age Group`, week_ending, ratio_m, lci, uci) %>%
  mutate(comparison = if_else(ratio_m >1, "greater than", "less than")) %>%
  significance_wk() %>%
  rename(date = week_ending)


#nrs by location
nrs_deaths_covid_week <- nrs_deaths_covid_raw %>% 
  filter(`Week beginning` == "Deaths involving COVID-194" | 
          Details %in% c("Care Home", "Home / Non-institution", "Hospital", "Other institution")) %>%
  pivot_longer(cols = `43829`:names(nrs_deaths_covid_raw)[ncol(nrs_deaths_covid_raw)-1],
               names_to = "week_beginning", 
               values_to = "weekly_deaths_total") %>%
  mutate(Details = case_when(`Week beginning` == "Deaths involving COVID-194" ~ "All",
                             TRUE ~ Details)) %>%
  mutate(week_beginning = janitor::excel_numeric_to_date(parse_number(week_beginning))) %>%
  mutate(Type = "Covid19 deaths") %>%
  rename("Location" = Details) %>%
  filter(Location != "Other institution") %>%
  select(Location, week_beginning, weekly_deaths_total, Type) %>%
  mutate(week_ending = week_beginning + 6)

wk_gr_nrs_deaths <- nrs_deaths_covid_week %>%
  group_by(Location) %>%
  mutate(week_ending_prev = lag(weekly_deaths_total, 1)) %>%
  filter(!is.na(week_ending_prev) & week_ending_prev >0) %>% 
  #pivot_longer(c(weekly_deaths_total,week_ending_prev), names_to = "week", values_to = "new_numbers_week") %>%
  #mutate(week = factor(week, levels = c("week_ending_prev", "weekly_deaths_total"))) %>%
  ungroup() %>%
  group_by(Location, week_ending) %>%
  nest() %>%
  mutate(tab = map(data, ~ weekly_ratios_ci(.x$weekly_deaths_total, .x$week_ending_prev))) %>%
  mutate(ratio_m = map_dbl(tab, ~parse_number(as.character((.x[1,2]))))) %>% 
  mutate(lci = map_dbl(tab, ~parse_number(as.character((.x[2,2]))))) %>% 
  mutate(uci = map_dbl(tab, ~parse_number(as.character((.x[3,2]))))) %>% 
  ungroup() %>%
  select(Location, week_ending, ratio_m, lci, uci) %>%
  mutate(comparison = if_else(ratio_m >1, "greater than", "less than")) %>%
  significance_wk() %>%
  rename(date = week_ending)

wk_gr_nrs_deaths <- left_join(wk_gr_nrs_deaths,
  nrs_deaths_covid_week %>% 
  filter(weekly_deaths_total >0) %>%
  rename("change" = weekly_deaths_total, 
         "date" = "week_ending") %>%
  select(change, date, Location))

wk_gr_newdeaths_latest <- wk_gr_newdeaths %>% mutate(source = "HPS", Location = "HPS") %>% filter(date == max(wk_gr_newdeaths$date))

wk_gr_nps_nrs <- bind_rows(wk_gr_newdeaths %>% mutate(source = "HPS")  %>%
                           filter(date %in% wk_gr_nrs_deaths$date), 
                           wk_gr_nrs_deaths %>% mutate(source = "NRS"))
wk_gr_nps_nrs <- wk_gr_nps_nrs %>%
                 mutate(Location = case_when( source == "HPS" ~ source, 
                                              Location == "All" ~ "NRS",
                                             TRUE ~ Location))
  
```


\newpage

\thispagestyle{empty}

```{r casesdeathsicuratios, fig.width=5.5, fig.height= 9, fig.cap="Ratios of weekly new cases, deaths, ICU occupancy and hospitalisations vs respective counts for previous week; graphics prepared by The University of Edinburgh"}
fig1 <- ggplot(wk_gr_newcases %>% filter(!is.na(ratio) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_blue, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_blue) +
  geom_point(colour = nice_blue, size = 1) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  scale_y_continuous(trans = "log10",
                         labels = scales::comma_format(accuracy = 1),
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        #title = "Change in weekly cases/deaths total as ratio of previous week",
        subtitle = "New Cases (Source: HPS)") +
  theme_bw(base_size = 10) +
  theme(plot.margin = unit(c(0.2,0.5,0.2,0.3), "cm"))

fig1_inset <- ggplot(wk_gr_newcases %>% filter(!is.na(ratio) & 
                    !is.infinite(ratio) & date >= max(wk_gr_newcases$date)-20)) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_blue, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_blue) +
  geom_point(colour = nice_blue, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d")) +
  scale_y_continuous(trans = "log10") +
  labs( x = "", y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig1 <- ggdraw() +
  draw_plot(fig1) +
  draw_plot(fig1_inset, x = 0.57, y = .54, width = .37, height = .3)

fig2 <- ggplot(wk_gr_newdeaths %>% filter(!is.na(ratio) & 
              !is.infinite(ratio) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_red, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_red) +
  geom_point(colour = nice_red, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        subtitle = "New Deaths (Source: HPS)") +
  theme_bw(base_size = 10) + 
  theme(plot.margin = unit(c(0.2,0.5,0.2,0.2), "cm"))

fig2_inset <- ggplot(wk_gr_newdeaths %>% filter(!is.na(ratio) & 
                    !is.infinite(ratio) & date >= max(wk_gr_newdeaths$date)-20)) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_red, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_red) +
  geom_point(colour = nice_red, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d"),expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig2 <- ggdraw() +
  draw_plot(fig2) +
  draw_plot(fig2_inset, x = 0.57, y = .54, width = .37, height = .3)


fig3 <- ggplot(wk_gr_hosp_icu %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_orange, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_orange) +
  geom_point(colour = nice_orange, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  labs( x = "Current Date",
        y = "Day-Of-The-Week Ratio",
        subtitle = "Patients in ICU (Source: NHS Boards)") +
  theme_bw(base_size = 10)  + 
  theme(plot.margin = unit(c(0.2,0.4,0.2,0.3), "cm"))



fig3_inset <- ggplot(wk_gr_hosp_icu %>% filter(!is.na(ratio_m) & 
                    !is.infinite(ratio_m) & date >= max(wk_gr_hosp_icu$date)-20)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_orange, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_orange) +
  geom_point(colour = nice_orange, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig3 <- ggdraw() +
  draw_plot(fig3) +
  draw_plot(fig3_inset, x = 0.57, y = .54, width = .37, height = .3)

fig4 <- ggplot(wk_gr_hosp_hosp %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_green, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.1) +
  geom_line(colour = nice_green) +
  geom_point(colour = nice_green, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  labs( x = "Current Date",
        y = "Day-Of-The-Week Ratio",
        subtitle = "Patients in Hospital (Source: NHS Boards)") +
  theme_bw(base_size = 10)  + 
  theme(plot.margin = unit(c(0.2,0.4,0.2,0.3), "cm"))

fig4_inset <- ggplot(wk_gr_hosp_hosp %>% filter(!is.na(ratio_m) & 
                    !is.infinite(ratio_m) & date >= max(wk_gr_hosp_hosp$date)-20)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_green, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_green) +
  geom_point(colour = nice_green, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig4 <- ggdraw() +
  draw_plot(fig4) +
  draw_plot(fig4_inset, x = 0.57, y = .54, width = .37, height = .3)

gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 4) 

```

```{r, fig.width=15, fig.height=9, fig.cap="Ratios of new cases, new deaths, ICU occupancy and hospitalisations vs respective counts for previous time period. Cases and deaths are comparisons of weekly sums; ICU occupancy and hospitalisations are week over week comparisons of daily counts. Graphics provided by The University of Edinburgh."}
gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 2, ncol = 2) 
```

```{r, fig.width=15, fig.height=9, fig.cap="Ratios of new cases, new deaths, ICU occupancy and hospitalisations vs respective counts for previous time period. Cases and deaths are comparisons of weekly sums; ICU occupancy and hospitalisations are week over week comparisons of daily counts. Graphics provided by The University of Edinburgh."}
png("weekly_ratios_landscape.png", width = 11.69, height = 8.27, units = "in", res = 400)
#gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 2, ncol = 2, bottom = "Ratios of new cases, new deaths, hospitalisations and ICU occupancy vs respective counts for previous time period. Cases and deaths are comparisons \nof weekly sums; Hospitalisations and ICU occupancy are week over week comparisons of daily counts. Graphics provided by The University of Edinburgh.")
gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 2, ncol = 2, bottom = "Weekly ratios for new cases and new deaths are ratios of weekly sums, plotted on a log10 scale.  Day-of-the-week ratios for hospitalisations and \nICU  occupancy are ratios of daily counts, measured 7 days apart and plotted on a log10 scale. Graphics provided by The University of Edinburgh.")
dev.off()
```

```{r fig.width=5.5, fig.height= 9, fig.cap="Ratios of new cases, new deaths, ICU occupancy and hospitalisations vs respective counts for previous time period. Cases and deaths are comparisons of weekly sums; ICU occupancy and hospitalisations are week over week comparisons of daily counts. Graphics provided by The University of Edinburgh."}
fig1 <- ggplot(wk_gr_newcases %>% filter(!is.na(ratio) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_blue, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_blue) +
  geom_point(colour = nice_blue, size = 1) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  scale_y_continuous(trans = "log10",
                         labels = scales::comma_format(accuracy = 1),
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        #title = "Change in weekly cases/deaths total as ratio of previous week",
        subtitle = "New Cases (Source: HPS)") +
  theme_bw(base_size = 10) +
  theme(plot.margin = unit(c(0.2,0.5,0.2,0.3), "cm"))

fig1_inset <- ggplot(wk_gr_newcases %>% filter(!is.na(ratio) & 
                    !is.infinite(ratio) & date >= max(wk_gr_newcases$date)-20)) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_blue, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_blue) +
  geom_point(colour = nice_blue, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d")) +
  scale_y_continuous(trans = "log10") +
  labs( x = "", y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig1 <- ggdraw() +
  draw_plot(fig1) +
  draw_plot(fig1_inset, x = 0.57, y = .54, width = .37, height = .3)

fig2 <- ggplot(wk_gr_newdeaths %>% filter(!is.na(ratio) & 
              !is.infinite(ratio) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_red, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_red) +
  geom_point(colour = nice_red, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        subtitle = "New Deaths (Source: HPS)") +
  theme_bw(base_size = 10) + 
  theme(plot.margin = unit(c(0.2,0.5,0.2,0.2), "cm"))

fig2_inset <- ggplot(wk_gr_newdeaths %>% filter(!is.na(ratio) & 
                    !is.infinite(ratio) & date >= max(wk_gr_newdeaths$date)-20)) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_red, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_red) +
  geom_point(colour = nice_red, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d"),expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig2 <- ggdraw() +
  draw_plot(fig2) +
  draw_plot(fig2_inset, x = 0.57, y = .54, width = .37, height = .3)


fig3 <- ggplot(wk_gr_hosp_icu %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_orange, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_orange) +
  geom_point(colour = nice_orange, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  labs( x = "Current Date",
        y = "Day-Of-The-Week Ratio",
        subtitle = "Patients in ICU (Source: NHS Boards)") +
  theme_bw(base_size = 10)  + 
  theme(plot.margin = unit(c(0.2,0.4,0.2,0.3), "cm"))



fig3_inset <- ggplot(wk_gr_hosp_icu %>% filter(!is.na(ratio_m) & 
                    !is.infinite(ratio_m) & date >= max(wk_gr_hosp_icu$date)-20)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_orange, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_orange) +
  geom_point(colour = nice_orange, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig3 <- ggdraw() +
  draw_plot(fig3) +
  draw_plot(fig3_inset, x = 0.57, y = .54, width = .37, height = .3)

fig4 <- ggplot(wk_gr_hosp_hosp %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_green, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.1) +
  geom_line(colour = nice_green) +
  geom_point(colour = nice_green, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d"),
               limits = c(dmy("23-03-2020"), NA)) +
  labs( x = "Current Date",
        y = "Day-Of-The-Week Ratio",
        subtitle = "Patients in Hospital (Source: NHS Boards)") +
  theme_bw(base_size = 10)  + 
  theme(plot.margin = unit(c(0.2,0.4,0.2,0.3), "cm"))

fig4_inset <- ggplot(wk_gr_hosp_hosp %>% filter(!is.na(ratio_m) & 
                    !is.infinite(ratio_m) & date >= max(wk_gr_hosp_hosp$date)-20)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_green, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_green) +
  geom_point(colour = nice_green, size = 1) +
  scale_x_date(date_breaks = "8 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig4 <- ggdraw() +
  draw_plot(fig4) +
  draw_plot(fig4_inset, x = 0.57, y = .54, width = .37, height = .3)

gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 4)  
```

```{r}
png("weekly_ratios_portrait.png", height = 11.69, width = 7, units = "in", res = 400)
#gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 4, bottom = "Ratios of new cases, new deaths, hospitalisations and ICU occupancy  vs respective \ncounts for previous time period. Cases and deaths are comparisons of weekly sums; \nHospitalisations and ICU occupancy are week over week comparisons of daily counts. \nGraphics provided by The University of Edinburgh.") 
gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 4, bottom = "Weekly ratios for new cases and new deaths are ratios of weekly sums, plotted on a log10 \nscale. Day-of-the-week ratios for hospitalisations and ICU occupancy are ratios of daily \ncounts, measured 7 days apart and plotted on a log10 scale. Graphics provided by \nThe University of Edinburgh.")
dev.off()
```

```{r}
png("weekly_ratios_portrait_4email.png", height = 11.69, width = 7, units = "in", res = 400)
gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 4, bottom = "Weekly ratios for new cases and new deaths are ratios of weekly sums, plotted on a log10 \nscale. Day-of-the-week ratios for number of patients in hospital and ICU are ratios of daily \ncounts, measured 7 days apart and plotted on a log10 scale. Figure insets highlight ratios\nand trends for the last 21 days. Graphics provided by The University of Edinburgh.")
dev.off()

tiff("weekly_ratios_portrait.tiff", height = 11.69, width = 7, units = "in", res = 400)
gridExtra::grid.arrange(fig1, fig2, fig4, fig3, nrow = 4, bottom = "Weekly ratios for new cases and new deaths are ratios of weekly sums, plotted on a log10 \nscale. Day-of-the-week ratios for hospital occupancy and ICU occupancy are ratios of daily \ncounts, measured 7 days apart and plotted on a log10 scale. Figure insets highlight more \nrecent ratios and trends. Graphics provided by The University of Edinburgh.")
dev.off()
```

```{r fig.width=5.5, fig.height= 9, fig.cap="Ratios of new cases, new deaths, ICU occupancy and hospitalisations vs respective counts for previous time period. Cases and deaths are comparisons of weekly sums; ICU occupancy and hospitalisations are week over week comparisons of daily counts. Graphics provided by The University of Edinburgh."}
adjusted <- read_excel("Adjusted ratios.xlsx", skip = 1) %>%
  select(Date, `Ratio...13`, `Lower...14`, `Upper...15`) %>%
  rename(ratio_m = `Ratio...13`, 
         lci = `Lower...14`, 
         uci = `Upper...15`) %>%
  mutate(date = ymd(Date)) %>%
  select(-Date) %>%
  filter(date %in% dmy(c("04/05/2020", "11/05/2020"))) %>%
  bind_rows(wk_gr_newdeaths %>% select(date, ratio_m) %>%filter(date %in% dmy(c("03/05/2020","05/05/2020", "10/05/2020", "12/05/2020"))))
#adjusted$date <-  ymd_h(paste(adjusted$date, "0")) + hours(4)

adjusted_1 <- filter(adjusted, date %in% dmy(c("03/05/2020","04/05/2020","05/05/2020"))) %>%
  mutate(type = "adjusted_1")
adjusted_2 <- filter(adjusted, date %in% dmy(c("10/05/2020","11/05/2020","12/05/2020"))) %>%
  mutate(type = "adjusted_2")
wk_gr_newdeaths <- wk_gr_newdeaths %>%
  mutate(type = "unadjusted")

wk_gr_newdeaths_adj <- bind_rows(wk_gr_newdeaths, adjusted_1, adjusted_2)

tiff("weekly_ratios_newdeaths_adjusted.tiff", height = 11.69/4, width = 5, units = "in", res = 400)
fig2 <- ggplot(wk_gr_newdeaths_adj %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci, colour = type, fill = type) +
  geom_errorbar(width = 0, alpha = 0.4, position=position_dodge(width=0.3)) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(position=position_dodge(width=0.3)) +
  geom_point(size = 0.5, position=position_dodge(width=0.3)) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d")) +
  scale_colour_manual(values = c("grey50", "grey51", "#D55E00")) +
  scale_fill_manual(values = c("grey50", "grey51", "#D55E00")) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        subtitle = "New Deaths (Source: HPS)") +
  theme_bw(base_size = 8) +
  theme(legend.position = "none")

fig2_inset <- ggplot(wk_gr_newdeaths_adj %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= max(wk_gr_newdeaths$date)-6)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci, colour = type, fill = type) +
  geom_errorbar(width = 0, alpha = 0.4, position=position_dodge(width=0.2)) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(position=position_dodge(width=0.2)) +
  geom_point(size = 1, position=position_dodge(width=0.2)) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "4 days", labels = date_format("%b %d"),expand = expansion(mult = 0.1)) +
  scale_colour_manual(values = c("grey51", "#D55E00")) +
  scale_fill_manual(values = c("grey51", "#D55E00")) +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"), 
        legend.position = "none")

fig2 <- ggdraw() +
  draw_plot(fig2) +
  draw_plot(fig2_inset, x = 0.57, y = .52, width = .40, height = .3)
fig2
dev.off()

tiff("weekly_ratios_newcases.tiff", height = 11.69/4, width = 5, units = "in", res = 400)
fig1 <- ggplot(wk_gr_newcases %>% filter(!is.na(ratio) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_blue, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_blue) +
  geom_point(colour = nice_blue, size = 1) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d")) +
  scale_y_continuous(trans = "log10",
                         labels = scales::comma_format(accuracy = 1),
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        #title = "Change in weekly cases/deaths total as ratio of previous week",
        subtitle = "New Cases (Source: HPS)") +
  theme_bw(base_size = 10) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 14, b = 0, l = 0)))

fig1_inset <- ggplot(wk_gr_newcases %>% filter(!is.na(ratio) & 
                    !is.infinite(ratio) & date >= max(wk_gr_newcases$date)-8)) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_blue, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_blue) +
  geom_point(colour = nice_blue, size = 1) +
  scale_x_date(date_breaks = "4 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "", y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig1 <- ggdraw() +
  draw_plot(fig1) +
  draw_plot(fig1_inset, x = 0.57, y = .52, width = .40, height = .3)

fig1
dev.off()


tiff("weekly_ratios_newdeaths.tiff", height = 11.69/4, width = 5, units = "in", res = 400)
fig2 <- ggplot(wk_gr_newdeaths %>% filter(!is.na(ratio) & 
              !is.infinite(ratio) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_red, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_red) +
  geom_point(colour = nice_red, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d")) +
  labs( x = "End Date of Current Week",
        y = "Weekly Ratio",
        subtitle = "New Deaths (Source: HPS)") +
  theme_bw(base_size = 10)

fig2_inset <- ggplot(wk_gr_newdeaths %>% filter(!is.na(ratio) & 
                    !is.infinite(ratio) & date >= max(wk_gr_newdeaths$date)-8)) +
  aes(x = date, y = ratio,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_red, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_red) +
  geom_point(colour = nice_red, size = 1) +
  scale_x_date(date_breaks = "4 days", labels = date_format("%b %d"),expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig2 <- ggdraw() +
  draw_plot(fig2) +
  draw_plot(fig2_inset, x = 0.57, y = .52, width = .40, height = .3)
fig2
dev.off()

tiff("dayofweek_ratios_icuoccup.tiff", height = 11.69/4, width = 5, units = "in", res = 400)
fig3 <- ggplot(wk_gr_hosp_icu %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_orange, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_orange) +
  geom_point(colour = nice_orange, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d")) +
  labs( x = "Current Date",
        y = "Day-Of-The-Week Ratio",
        subtitle = "ICU Occupancy (Source: NHS Boards)") +
  theme_bw(base_size = 10) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 7, b = 0, l = 0)))



fig3_inset <- ggplot(wk_gr_hosp_icu %>% filter(!is.na(ratio_m) & 
                    !is.infinite(ratio_m) & date >= max(wk_gr_hosp_icu$date)-8)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_orange, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_orange) +
  geom_point(colour = nice_orange, size = 1) +
  scale_x_date(date_breaks = "4 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig3 <- ggdraw() +
  draw_plot(fig3) +
  draw_plot(fig3_inset, x = 0.57, y = .52, width = .40, height = .3)
fig3
dev.off()

tiff("dayofweek_ratios_hospoccup.tiff", height = 11.69/4, width = 5, units = "in", res = 400)

fig4 <- ggplot(wk_gr_hosp_hosp %>% filter(!is.na(ratio_m) & 
              !is.infinite(ratio_m) & date >= dmy("23-03-2020"))) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_green, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_green) +
  geom_point(colour = nice_green, size = 1) +
  scale_y_continuous(trans = "log10",
                         #breaks = breaks,
                         expand = expansion(mult = 0.1)) +
  scale_x_date(date_breaks = "1 week", labels = date_format("%b %d")) +
  labs( x = "Current Date",
        y = "Day-Of-The-Week Ratio",
        subtitle = "Hospital Occupancy (Source: NHS Boards)") +
  theme_bw(base_size = 10) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 14, b = 0, l = 0)))


fig4_inset <- ggplot(wk_gr_hosp_hosp %>% filter(!is.na(ratio_m) & 
                    !is.infinite(ratio_m) & date >= max(wk_gr_hosp_hosp$date)-8)) +
  aes(x = date, y = ratio_m,
    ymin = lci, ymax = uci) +
  geom_errorbar(width = 0, colour = nice_green, alpha = 0.4) +
  geom_hline(yintercept = 1, colour = "red", linetype = "dashed", size = 0.2) +
  geom_line(colour = nice_green) +
  geom_point(colour = nice_green, size = 1) +
  scale_x_date(date_breaks = "4 days", labels = date_format("%b %d"), expand = expansion(mult = 0.1)) +
  scale_y_continuous(trans = "log10") +
  labs( x = "",
        y = "") +
  theme_bw(base_size = 8) +
  theme(plot.margin = margin(0, 0, -1, 0, "cm"))

fig4 <- ggdraw() +
  draw_plot(fig4) +
  draw_plot(fig4_inset, x = 0.57, y = 0.52, width = 0.40, height = 0.3)

fig4
dev.off()
```



